config/routes.rb
Rails.application.routes.draw do

  # home
  root 'home#top'
  get '/about' => 'home#about'

  # users
  devise_for :users
  resources :users, only: [:update], param: :user_id
  resources :users, only: [] do
    resources :comments, only: [:index]
    resources :issues, only: [:index]
  end
  get 'mypage/:user_id' => 'users#mypage', as: "mypage"
  get 'mypage/:user_id/edit' => 'users#edit', as: "edit_user"
  post 'mypage/:user_id/join_team' => 'users#join_team', as: "join_team"

  # search
  get 'teams/:team_id/issues/search' => 'search#issues', as: "team_issues_search"
  get 'teams/:team_id/users/search' => 'search#users', as: "team_users_search"
  get 'teams/:team_id/tags/search' => 'search#tags', as: "team_tags_search"

  # teams
  resources :teams, only: [:show], param: :team_id
  resources :teams, only: [] do
  # teams/users
    resources :users, only: [:index, :show], param: :user_id
    resources :users, only: [] do
      resources :comments, only: [:index]
      resources :issues, only: [:index]
    end
  # teams/tags
    resources :tags, only: [:index, :create] do
      resources :issues, only: [:index]
    end
  # teams/issues
    resources :issues, param: :issue_id
    resources :issues, only: [] do
      resources :comments, only: [:create, :edit, :update, :destroy], param: :comment_id
      resource :likes, only: [:create, :destroy]
    end
    get '/issues/:issue_id/choice' => 'issues#choice', as: "choice"
    get '/issues/:issue_id/confirm' => 'issues#confirm', as: "confirm"
    put '/issues/:issue_id/settled' => 'issues#settled', as: "settled"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates	:comment, presence: true

  belongs_to :user
  belongs_to :issue

  has_one :response_evaluation, dependent: :destroy
  has_one :required_time_evaluation, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :only_team_user
  before_action :only_current_user, only: [:edit, :update, :destroy]

  def create
    issue = Issue.find(params[:issue_id])
    comment = Comment.new(comment_params)
    comment.user = current_user
    comment.issue_id = params[:issue_id]
    comment.is_first = true if issue.comments.where(user_id: current_user).blank?
    if comment.save(comment_params)
      if comment.is_first == true
        response = ResponseEvaluation.new
        create_response_evaluation(response, comment)
      end
    else
      flash[:error] = "コメントが空欄のようです。もう一度お試しください。"
    end
    redirect_back(fallback_location: root_path)
  end

  def edit
    @page_title = "Edit comment"
  end

  def update
    if @comment.update(comment_params)
      redirect_to team_issue_path(params[:team_id], params[:issue_id])
    else
      flash[:error] = "コメントが空欄のようです。もう一度お試しください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if @comment.destroy
      if @issue.comments.where(user_id: current_user).present?
        oldest_comment = @issue.comments.where(user_id: current_user).order("created_at").min
        oldest_comment.update(is_first: true)
        response = ResponseEvaluation.new
        create_response_evaluation(response, oldest_comment)
      end
    else
      flash[:error] = "コメントが削除できませんでした。もう一度お試しください。"
    end
    redirect_to team_issue_path(params[:team_id], params[:issue_id])
  end

  private
  def only_team_user
    unless TeamMember.where(team_id: @team).any? {|team| team.user_id == current_user.id}
      redirect_to mypage_path(current_user)
    end
  end

  def only_current_user
    unless @comment.user == current_user
      redirect_to team_path(@team)
    end
  end

  def comment_params
    params.require(:comment).permit(:user_id, :issue_id, :comment)
  end

  def create_response_evaluation(response, comment)
    response.user = current_user
    response.comment = comment
    response.created_issue_at = comment.issue.created_at
    response.first_comment_created_at = Time.current
    semi_difference = response.first_comment_created_at - response.created_issue_at
    response.difference = (semi_difference / 60).ceil
    response.save
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_choice_comment_card.html.erb
<div class="card callout-dark mt-3">
  <div class="row no-gutters">

    <div class="my-auto ml-3">
      <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: "50x50", class:"rounded-circle" %>
    </div>

    <div class="card-body">
      <span class="card-text"><%= comment.comment %></span>
      <div class="float-right">
        <%= link_to "☆", team_confirm_path(@team, @issue, comment_id: comment), class:"text-warning h3" %>
      </div>
    </div>

  </div>
</div>

app/views/comments/_comment_card.html.erb
<% if comment.has_best_answer == true %>
  <div class="card callout-coral mt-3">
<% else %>
  <div class="card callout-dark mt-3">
<% end %>

  <div class="card-body">
<!-- body -->
    <div class="row">
      <div class="col-9">
        <span class="card-text mt-3">
          <%= simple_format(comment.comment) %>
        </span>
      </div>

      <div class="col-3">
        <% if comment.has_best_answer == true %>
          <span class="badge badge-primary align-middle" style="background-color:#ff7f50;">
            Best answer
          </span>
        <% end %>
      </div>
    </div>
<!-- buttones -->
    <div class="row px-3 mt-1">
      <small class="text-muted mr-auto">
        <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
      </small>

        <%= link_to team_user_path(team, comment.user) do %>
          <%= attachment_image_tag comment.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "noimage.jpg", size: "30x30", class:"rounded-circle" %>
          <%= comment.user.name %>
        <% end %>

        <% if !issue.has_settled && comment.user == current_user && action_name == 'show' %>
          <%= link_to edit_team_issue_comment_path(team, issue, comment), class: "btn btn-outline-success btn-sm mx-1" do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to team_issue_comment_path(team, issue, comment), method: :delete, data: { confirm: "will you delete it?"}, class: "btn btn-outline-danger btn-sm" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
    </div>

  </div>
</div>

app/views/comments/_confirm_comment_card.html.erb
<div class="card callout-dark mt-3">
  <div class="row no-gutters">

    <div class="my-auto ml-3">
      <%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size: "50x50", class:"rounded-circle" %>
    </div>

    <div class="card-body">
      <span class="card-text"><%= comment.comment %></span>
    </div>

  </div>
</div>

app/views/comments/edit.html.erb
<div class="row">
  <div class="offset-2 col-8">
    <%= form_with model: [@team, @issue, @comment] do |f| %>

      <p class="headline mt-5">Comment</p>
      <div class="form-group">
        <%= f.text_area :comment, class:"form-control offset-1 col-10" %>
      </div>

      <div class="row flex-column align-items-center mt-5">
        <span class="titlemark"><%= flash[:error] %></span>
      </div>

      <%= f.submit "Update comment", class:"btn btn-dark btn-block offset-1 col-10" %>
    <% end %>

    <div class="row flex-column align-items-end">
      <%= link_to team_issue_comment_path(@team, @issue, @comment), method: :delete, data: { confirm: "will you delete it?"}, class:"btn btn-outline-danger mt-5" do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
</div>