config/routes.rb
Rails.application.routes.draw do

  # home
  root 'home#top'
  get '/about' => 'home#about'

  # users
  devise_for :users
  resources :users, only: [:update], param: :user_id
  resources :users, only: [] do
    resources :comments, only: [:index]
    resources :issues, only: [:index]
  end
  get 'mypage/:user_id' => 'users#mypage', as: "mypage"
  get 'mypage/:user_id/edit' => 'users#edit', as: "edit_user"
  post 'mypage/:user_id/join_team' => 'users#join_team', as: "join_team"

  # search
  get 'teams/:team_id/issues/search' => 'search#issues', as: "team_issues_search"
  get 'teams/:team_id/users/search' => 'search#users', as: "team_users_search"
  get 'teams/:team_id/tags/search' => 'search#tags', as: "team_tags_search"

  # teams
  resources :teams, only: [:show], param: :team_id
  resources :teams, only: [] do
  # teams/users
    resources :users, only: [:index, :show], param: :user_id
    resources :users, only: [] do
      resources :comments, only: [:index]
      resources :issues, only: [:index]
    end
  # teams/tags
    resources :tags, only: [:index, :create] do
      resources :issues, only: [:index]
    end
  # teams/issues
    resources :issues, param: :issue_id
    resources :issues, only: [] do
      resources :comments, only: [:create, :edit, :update, :destroy], param: :comment_id
      resource :likes, only: [:create, :destroy]
    end
    get '/issues/:issue_id/choice' => 'issues#choice', as: "choice"
    get '/issues/:issue_id/confirm' => 'issues#confirm', as: "confirm"
    put '/issues/:issue_id/settled' => 'issues#settled', as: "settled"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
	validates	:title, presence: true
	validates	:body, presence: true

	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings

  belongs_to :user
	belongs_to :team

	# PV count
	is_impressionable

	def likes_by?(user)
		likes.find_by(user_id: user.id).present?
	end

	def self.search(team, target, status, q)
		if target == "title"
      splited_q = q.split(/[[:blank:]]+/)
      issues = []
      splited_q.each do |q|
        next if q == ""
        issues += team.issues.where('LOWER(title) LIKE ?', "%#{q}%".downcase)
      end
      # order、reveseで新しい順にしたいけどできなかったTT
      # orderかpageにnomethod error
      issues.uniq!
      issues = issues.select{|issue| issue.has_settled == true} if status == "settled"
      issues = issues.select{|issue| issue.has_settled == false} if status == "unsettled"
    elsif target == "body"
      splited_q = q.split(/[[:blank:]]+/)
      issues = []
      splited_q.each do |q|
        next if q == ""
        issues += team.issues.where('LOWER(body) LIKE ?', "%#{q}%".downcase)
      end
      issues.uniq!
      issues = issues.select{|issue| issue.has_settled == true} if status == "settled"
      issues = issues.select{|issue| issue.has_settled == false} if status == "unsettled"
    elsif target == "tag"
      splited_q = q.split(/[[:blank:]]+/)
      issues = []
      splited_q.each do |q|
        next if q == ""
        issues += team.issues.joins(:tags).where('LOWER(tags.name) LIKE ?', "%#{q}%".downcase)
      end
      issues.uniq!
      issues = issues.select{|issue| issue.has_settled == true} if status == "settled"
      issues = issues.select{|issue| issue.has_settled == false} if status == "unsettled"
    elsif target == "user"
      splited_q = q.split(/[[:blank:]]+/)
      issues = []
      splited_q.each do |q|
        next if q == ""
        issues += team.issues.joins(:user).where('LOWER(users.name) LIKE ?', "%#{q}%".downcase)
      end
      issues.uniq!
      issues = issues.select{|issue| issue.has_settled == true} if status == "settled"
      issues = issues.select{|issue| issue.has_settled == false} if status == "unsettled"
    else
      issues = team.issues
      issues = issues.where(has_settled: true) if status == "settled"
      issues = issues.where(has_settled: false) if status == "unsettled"
    end
      return issues
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :only_team_user
  before_action :only_current_user, except: [:new, :create, :index, :show]

  impressionist :actions => [:show]

  def new
    @page_title = "New issue"
  end

  def create
    issue = Issue.new(issue_params)
    issue.team = @team
    issue.user = current_user
    if issue.save
      if params[:tagging]
          params[:tagging][:tag_ids].each do |tag|
          tagging = Tagging.new
          tagging.tag_id = tag
          tagging.issue = issue
          tagging.save
        end
      end
    else
      flash.now[:error] = "タイトルか本文が空欄のようです。もう一度お試しください。"
      render :new
    end
      redirect_to team_issue_path(@team, issue)
  end

  def index
    @page_title = "Issues"
    if @team.present? && @user.present?
      issues = @team.issues.where(user_id: @user).order(created_at: :desc)
    elsif @team.present? && @tag.present?
      issues = @tag.issues.order(created_at: :desc)
    elsif @team.present?
      issues = @team.issues.order(created_at: :desc)
    else
      issues = @user.issues.order(created_at: :desc)
    end
    @pagenated_issues = issues.page(params[:page]).per(10)
  end

  def show
    @page_title = "Issue"
    @new_comment = Comment.new
    @comments = @issue.comments
    impressionist(@issue, nil, unique: [:user_id])
  end

  def edit
    @page_title = "Edit issue"
  end

  def update
    if @issue.update(issue_params)
      redirect_to team_issue_path(@team, @issue)
    else
      flash[:error] = "タイトルか本文が空欄のようです。もう一度お試しください。"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    unless @issue.destroy
      flash[:error] = "イシューが削除されませんでした。もう一度お試しください。"
      redirect_back(fallback_location: root_path)
    end
    redirect_to team_issues_path(@team)
  end

  def choice
    @page_title = "Choose the best answer."
    if @issue.comments == []
      flash[:error] = "この問題にはまだコメントがされていません。もう少し待ちましょう。"
      redirect_back(fallback_location: root_path)
    end
    @comments = @issue.comments
  end

  def confirm
    @page_title = "Once you decide, you can't undo."
  end

  def settled
    @issue.update(has_settled: true)
    @comment.update(has_best_answer: true)
    evaluated_comments = @issue.comments.where(is_first: true)
    create_required_time_evaluation(evaluated_comments)
    redirect_to team_issue_path(@team)
  end

  private
  def only_team_user
    unless TeamMember.where(team_id: @team).any? {|team| team.user_id == current_user.id}
      redirect_to mypage_path(current_user)
    end
  end

  def only_current_user
    unless @issue.user == current_user
      redirect_to team_path(@team)
    end
  end

  def issue_params
    params.require(:issue).permit(:user_id, :team_id, :title, :body, :has_settled, :settled_at, {tag_ids: []} )
  end

  def create_required_time_evaluation(evaluated_comments)
    evaluated_comments.each do |comment|
      required_time = RequiredTimeEvaluation.new
      required_time.user = comment.user
      required_time.comment = comment
      required_time.first_comment_created_at = comment.created_at
      required_time.issue_settled_at = @issue.updated_at
      semi_difference = required_time.issue_settled_at - required_time.first_comment_created_at
      required_time.difference = (semi_difference / 60).ceil
      required_time.save
    end
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with model: [team, issue] do |f| %>

  <p class="headline pb-2">Tags</p>
  <p class="mb-3">
    <span class="rounded border border-dark bg-dark text-white px-1">Selected</span>
    <span class="rounded border border-dark px-1">Unselected</span>
  </p>
  <div class="form-group checkboxes">
    <%= f.collection_check_boxes :tag_ids, team.tags, :id, :name, include_hidden: false do |tag| %>
      <%= tag.check_box %>
      <%= tag.label %>
    <% end %>
  </div>
  <div class="row flex-column align-items-end">
    <%= link_to team_tags_path(team), class:"btn btn-danger btn-sm" do %>
      Create new tag
      <i class="fas fa-external-link-alt"></i>
    <% end %>
  </div>

  <p class="headline mt-5">Title</p>
  <div class="form-group">
    <%= f.text_field :title, class:"form-control offset-1 col-10" %>
  </div>

  <p class="headline mt-5">Text</p>
  <div class="form-group">
    <%= f.text_area :body, class:"form-control offset-1 col-10" %>
  </div>

  <div class="row flex-column align-items-center mt-5">
    <span class="titlemark"><%= flash[:error] %></span>
  </div>

  <% if action_name == 'new' %>
    <%= f.submit "Create", class:"btn btn-dark btn-dark offset-2 col-8" %>
  <% elsif action_name == 'edit' %>
    <%= f.submit "Update", class:"btn btn-dark btn-dark offset-2 col-8" %>
  <% end %>
<% end %>

app/views/issues/_index_card.html.erb
<div class="col-12">
  <% if issue.has_settled == true %>
    <div class="card callout-coral">
  <% else %>
    <div class="card callout-dark">
  <% end %>

    <div class="card-body px-4">

      <div class="card-title m-0">
        <strong>
          <%= link_to issue.title, team_issue_path(team, issue) %>
        </strong>

        <% if issue.has_settled == true %>
          <p class="badge badge-primary m-0" style="background-color:#ff7f50;">
            Solved
          </p>
        <% end %>

        <p class="float-right m-0">
          <i class="fas fa-eye"></i>
          <%= issue.impressionist_count %>

          <i class="fas fa-comment"></i>
          <%= issue.comments.count %>

          <span id="like_btn_<%= issue.id %>">
            <%= render 'likes/like_btn', team: team, issue: issue %>
          </span>
        </p>
      </div>

      <div class="card-subtitle my-2">
        <% issue.tags.each do |tag| %>
          <%= link_to tag.name, team_tag_issues_path(team, tag), class:"btn btn-sm btn-dark py-0" %>
        <% end %>
      </div>

      <div class="card-text d-flex justify-content-between">
        <small class="text-muted">
          <%= issue.created_at.strftime('%Y/%m/%d %H:%M') %>
        </small>

        <%= link_to team_user_path(team, issue.user) do %>
          <%= attachment_image_tag issue.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "noimage.jpg", size:"30x30", class:"rounded-circle" %>
          <%= issue.user.name %>
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/issues/_search_form.html.erb
<div class="search offset-1 col-10 mb-5">
  <%= form_with url: team_issues_search_path(team), method: :get, local: true do |f| %>
    <div class="row form-group mb-0">
      <%= f.select :target, [["Title", "title"], ["Text", "body"], ["Tag", "tag"], ["User", "user"]], {include_blank: "Unselected"}, {class:'custom-select col-12 col-md-4'} %>

      <div class="form-group radiobuttons mt-1 ml-1 ml-md-3">
        <%= f.radio_button :status,  "", id: "status" %>
        <%= f.label :has_settled, "Status", for: "status" %>
        <%= f.radio_button :status,  "settled", id: "settled" %>
        <%= f.label :has_settled, "Solved", for: "settled" %>
        <%= f.radio_button :status,  "unsettled", id: "unsettled" %>
        <%= f.label :has_settled, "Unsolved", for: "unsettled" %>
      </div>
    </div>

    <div class="row input-group">
      <%= f.text_field :q, placeholder: "Enter search word.", class:"form-control" %>
      <div class="input-group-append">
        <%= f.submit "Search", class:"btn btn-danger" %>
      </div>
    </div>

    <div class="row justify-content-end">
      <%= link_to "Delete search conditions", team_issues_path(@team) %>
    </div>
  <% end %>
</div>

app/views/issues/_show_card.html.erb
<% if issue.has_settled == true %>
  <div class="card callout-coral">
<% else %>
  <div class="card callout-dark">
<% end %>

  <div class="card-body">

<!-- title / like -->
    <div class="card-title">
      <span class="h3"><%= issue.title %></span>

      <% if issue.has_settled == true %>
        <p class="badge badge-primary align-middle" style="background-color:#ff7f50;">
          Solved
        </p>
      <% end %>

      <p class="float-right m-0">
        <i class="fas fa-eye"></i>
        <%= issue.impressionist_count %>

        <i class="fas fa-comment"></i>
        <%= issue.comments.count %>

        <span id="like_btn_<%= issue.id %>">
          <% if controller.action_name == 'show' %>
            <%= render 'likes/like_btn', team: team, issue: issue %>
          <% end %>
        </span>
      </p>
    </div>

<!-- tags -->
    <h6 class="card-subtitle mb-2 text-muted">
      <% issue.tags.each do |tag| %>
        <%= link_to tag.name, team_tag_issues_path(team, tag), class: "btn btn-dark btn-sm py-0" %>
      <% end %>
    </h6>

<!-- body -->
    <p class="card-text mt-3">
      <%= simple_format(issue.body) %>
    </p>

<!-- buttones -->
    <small class="text-muted">
      <%= issue.created_at.strftime('%Y/%m/%d %H:%M') %>
    </small>

    <div class="float-right">
      <%= link_to team_user_path(team, issue.user) do %>
        <%= attachment_image_tag issue.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "noimage.jpg", size: "30x30", class:"rounded-circle" %>
        <%= issue.user.name %>
      <% end %>

      <% if !issue.has_settled && issue.user == current_user && action_name == 'show' %>
        <%= link_to edit_team_issue_path(team, issue), class: "btn btn-outline-success btn-sm mx-1" do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to team_issue_path(team, issue), method: :delete, data: { confirm: "will you delete it?"}, class: "btn btn-outline-danger btn-sm" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/issues/choice.html.erb
<div class="row">
  <div class="offset-1 col-10">
    <%= render 'show_card', team: @team, issue: @issue %>
  </div>
</div>

<div class="row my-5">
  <div class="offset-2 col-8">
    <% @comments.each do |comment| %>
      <%= render 'comments/choice_comment_card', team: @team, issue: @issue, comment: comment %>
    <% end %>
  </div>
</div>

app/views/issues/confirm.html.erb
<div class="row">
  <div class="offset-1 col-10">
    <%= render 'show_card', team: @team, issue: @issue %>
  </div>
</div>

<div class="row my-5">
  <div class="offset-2 col-8">
    <%= render 'comments/confirm_comment_card', team: @team, issue: @issue, comment: @comment %>
  </div>
</div>

<div class="row mb-5">
  <div class="offset-3 col-6">
    <%= link_to "It's done !", team_settled_path(@team, @issue, comment_id: @comment), method: :put, class:"btn btn-danger btn-block" %>
  </div>
</div>

app/views/issues/edit.html.erb
<div class="row">
  <div class="offset-2 col-8">
    <%= render 'issues/form', team: @team, issue: @issue %>
  </div>
</div>

app/views/issues/index.html.erb
<div class="offset-1 col-10">
  <%= render 'issues/search_form', team: @team %>

  <% @pagenated_issues.each do |issue| %>
    <div class="row mt-3">
      <%= render 'issues/index_card', team: @team, issue: issue %>
    </div>
  <% end %>
</div>

<div class="row justify-content-center my-5">
  <%= paginate @pagenated_issues %>
</div>

app/views/issues/new.html.erb
<div class="row">
  <div class="offset-2 col-8">
    <%= render 'issues/form', team: @team, issue: Issue.new %>
  </div>
</div>

app/views/issues/show.html.erb
<!-- issue -->
<div class="row">
  <div class="offset-1 col-10">
    <%= render 'show_card', team: @team, issue: @issue %>
  </div>
</div>

<!-- comments -->
<div class="row mt-5">
  <div class="offset-2 col-8">
    <% @comments.each do |comment| %>
      <%= render 'comments/comment_card', team: @team, issue: @issue, comment: comment %>
    <% end %>
  </div>
</div>

<!-- comment form -->
<div class="row mt-3">
  <div class="offset-3 col-6">
    <span class="titlemark"><%= flash[:error] %></span>

    <% if !@issue.has_settled %>
      <%= form_with model: @new_comment, url: team_issue_comments_path(@team, @issue) do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, class: "form-control" %>
          <%= f.submit :post, class: "btn btn-sm btn-dark float-right mt-1" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<% if !@issue.has_settled && @issue.user == current_user && action_name == 'show' %>
  <div class="row flex-column align-items-center mt-5">
    <strong>Is the issue solved?</strong>
  </div>
    <div class="offset-4 col-4">
      <%= link_to "Choose the best answer.", team_choice_path(@team, @issue), class: "btn btn-danger btn-block mb-5" %>
    </div>
  </div>
<% end %>

<%= link_to "<< Back to Issues", team_issues_path(@team), class:"btn btn-sm btn-dark mb-3" %>