config/routes.rb
Rails.application.routes.draw do

  # home
  root 'home#top'
  get '/about' => 'home#about'

  # users
  devise_for :users
  resources :users, only: [:update], param: :user_id
  resources :users, only: [] do
    resources :comments, only: [:index]
    resources :issues, only: [:index]
  end
  get 'mypage/:user_id' => 'users#mypage', as: "mypage"
  get 'mypage/:user_id/edit' => 'users#edit', as: "edit_user"
  post 'mypage/:user_id/join_team' => 'users#join_team', as: "join_team"

  # search
  get 'teams/:team_id/issues/search' => 'search#issues', as: "team_issues_search"
  get 'teams/:team_id/users/search' => 'search#users', as: "team_users_search"
  get 'teams/:team_id/tags/search' => 'search#tags', as: "team_tags_search"

  # teams
  resources :teams, only: [:show], param: :team_id
  resources :teams, only: [] do
  # teams/users
    resources :users, only: [:index, :show], param: :user_id
    resources :users, only: [] do
      resources :comments, only: [:index]
      resources :issues, only: [:index]
    end
  # teams/tags
    resources :tags, only: [:index, :create] do
      resources :issues, only: [:index]
    end
  # teams/issues
    resources :issues, param: :issue_id
    resources :issues, only: [] do
      resources :comments, only: [:create, :edit, :update, :destroy], param: :comment_id
      resource :likes, only: [:create, :destroy]
    end
    get '/issues/:issue_id/choice' => 'issues#choice', as: "choice"
    get '/issues/:issue_id/confirm' => 'issues#confirm', as: "confirm"
    put '/issues/:issue_id/settled' => 'issues#settled', as: "settled"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :team_members, dependent: :destroy
  has_many :teams, through: :team_members
  has_many :issues, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :response_evaluations, dependent: :destroy
  has_many :required_time_evaluations, dependent: :destroy

  attachment :profile_image

  def self.search(team, q)
    splited_q = q.split(/[[:blank:]]+/)

    users = []
    splited_q.each do |q|
      next if q == ""
      users += team.users.where('LOWER(name) LIKE ?', "%#{q}%".downcase).order(created_at: :desc)
    end
    users.uniq!
    return users
  end

  def time_related_evaluation(evaluation_type)
    user_averages = evaluation_type.group(:user_id).average(:difference).map{|k,v| [k, v.to_i]}.to_h
    criteria = calculate_evaluation_criteria(user_averages)
    return [[0], [0]] unless criteria
    calculate_evaluation_datas_sort_by_max(criteria, user_averages)
  end

  def like_evaluation_datas
    # 標本不足により、総数で算出
    user_issues_array = User.joins(:issues).group("users.id").map{|user| [user.id, user.issue_ids]}.to_h
    like_count_array = user_issues_array.map{|user,issues| [user, issues.map{|issue| Issue.find(issue).likes.count}.sum]}.to_h
    criteria = calculate_evaluation_criteria(like_count_array)
    return [[0], [0]] unless criteria
    calculate_evaluation_datas_sort_by_min(criteria, like_count_array)
  end

  def best_answer_evaluation_datas
    # 標本不足により、総数で算出
    best_answer_count_array = Comment.group(:user_id).where(has_best_answer: true).count
    criteria = calculate_evaluation_criteria(best_answer_count_array)
    return [[0], [0]] unless criteria
    calculate_evaluation_datas_sort_by_min(criteria, best_answer_count_array)
  end

  def issue_viewed_evaluation_datas
    # 標本不足により、総数で算出
    user_issue_viewed_count = User.joins(issues: :impressions).group("users.id").count
    criteria = calculate_evaluation_criteria(user_issue_viewed_count)
    return [[0], [0]] unless criteria
    calculate_evaluation_datas_sort_by_min(criteria, user_issue_viewed_count)
  end

  def calculate_evaluation_criteria(evaluation_base)
    return false if evaluation_base.all? {|k,v| v == 0}

    # 階級幅の計算
    min = evaluation_base.values.min
    max = evaluation_base.values.max
    diff = max - min
    interval = (diff / 10.0).round
    return min, max, interval
  end

  def calculate_evaluation_datas_sort_by_max(criteria, user_evaluations)
    # 個体値が低いと高得点
    min = criteria[0]
    max = criteria[1]
    interval = criteria[2]
    evaluation_classes = []
    i = min

    10.times{|n|
      evaluation_classes << i
      i += interval
    }
    evaluation_classes << max

    validation_included_user = validation_included_user(evaluation_classes, user_evaluations)
    validation_included_user[0].reverse!
    validation_included_user[1].reverse!
    user_score = calculate_user_score(validation_included_user[1])

    return validation_included_user[0], user_score
  end

  def calculate_evaluation_datas_sort_by_min(criteria, user_evaluations)
    # 個体値が高いと高得点
    min = criteria[0]
    max = criteria[1]
    interval = criteria[2]
    evaluation_classes = []
    i = max

    10.times{|n|
      evaluation_classes << i
      i -= interval
    }
    evaluation_classes << min
    evaluation_classes.reverse!

    validation_included_user = validation_included_user(evaluation_classes, user_evaluations)
    user_score = calculate_user_score(validation_included_user[1])

    return validation_included_user[0], user_score
  end

  def validation_included_user(evaluation_classes, user_evaluations)
    evaluation_datas = []
    user_included_status = []
    i = 0
    n = 0
    m = 0

    10.times{|m|
      n = evaluation_classes[i]
      i += 1
      m = evaluation_classes[i]

      if i == 10
        validation_included_user = user_evaluations.select{|k,v| (n..m) === v}
      else
        validation_included_user = user_evaluations.select{|k,v| (n...m) === v}
      end
      evaluation_datas << validation_included_user.count

      if validation_included_user.any? {|k,v| k == self.id}
        user_included_status << 1
      else
        user_included_status << 0
      end
    }
    return evaluation_datas, user_included_status
  end

  def calculate_user_score(score_base)
    score_base.each_with_index{|status, i|
      return user_score = i+1 if status == 1
    }
  end

  def issue_tags_labels
    user_issue_tags_array = self.issues.map{|issue| issue.tags.map{|tag| tag.name}}.flatten
    return tags_name = ["nothing issues tags"] if user_issue_tags_array == []
    tags_name = user_issue_tags_array.group_by(&:itself).keys
  end

  def issue_tags_evaluation_datas
    user_issue_tags_array = self.issues.map{|issue| issue.tags.map{|tag| tag.id}}.flatten
    return evaluation_datas = [100] if user_issue_tags_array == []
    tags_count_array = user_issue_tags_array.group_by(&:itself).map{|k,v| [k, v.count]}.to_h
    base = tags_count_array.values.sum.to_f
    evaluation_datas = tags_count_array.map{|k,v| ((v / base)*100).to_i}
  end

  def comment_tags_labels
    user_comment_tags_array = self.comments.map{|comment| comment.issue.tags.map{|tag| tag.name}}.flatten
    return tags_name = ["nothing comments tags"] if user_comment_tags_array == []
    tags_name = user_comment_tags_array.group_by(&:itself).keys
  end

  def comment_tags_evaluation_datas
    user_comment_tags_array = self.comments.map{|comment| comment.issue.tags.map{|tag| tag.id}}.flatten
    return evaluation_datas = [100] if user_comment_tags_array == []
    tags_count_array = user_comment_tags_array.group_by(&:itself).map{|k,v| [k, v.count]}.to_h
    base = tags_count_array.values.sum.to_f
    evaluation_datas = tags_count_array.map{|k,v| ((v / base)*100).to_i}
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_team_user, only: [:index, :show]
  before_action :only_current_user, only: [:edit, :update, :mypage]
  before_action :barrier_trial_user, only: [:edit, :update]

  def mypage
    @page_title = "My page"
    @teams = current_user.teams.reverse
    @new_team_mamber = TeamMember.new
    chart_datas
  end

  def join_team
    team_name = params[:team_member][:team_name]
    team_id = params[:team_member][:team_id]
    team = Team.find_by(id: team_id, name: team_name)
    if team.present?
      team_member = TeamMember.new(team_member_params)
      team_member.user = current_user
      team_member.team = team
      team_member.save
      redirect_to team_issues_path(team)
    else
      @join_team = TeamMember.new
      flash[:error] = "The team is not found."
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @page_title = "User information"
    chart_datas
  end

  def chart_datas
    # chart.jsに渡す変数
    @user_scores = []
    gon.user_name = @user.name
    # response
    calculate_evaluation_data = @user.time_related_evaluation(ResponseEvaluation)
    gon.response_evaluation_datas = calculate_evaluation_data[0]
    @user_scores << calculate_evaluation_data[1]
    # required time
    calculate_evaluation_data = @user.time_related_evaluation(RequiredTimeEvaluation)
    gon.required_time_evaluation_datas = calculate_evaluation_data[0]
    @user_scores << calculate_evaluation_data[1]
    # like
    calculate_evaluation_data = @user.like_evaluation_datas
    gon.like_evaluation_datas = calculate_evaluation_data[0]
    @user_scores << calculate_evaluation_data[1]
    # best answer
    calculate_evaluation_data = @user.best_answer_evaluation_datas
    gon.best_answer_evaluation_datas = calculate_evaluation_data[0]
    @user_scores << calculate_evaluation_data[1]
    # issue viewed count
    calculate_evaluation_data = @user.issue_viewed_evaluation_datas
    gon.issue_viewed_evaluation_datas = calculate_evaluation_data[0]
    @user_scores << calculate_evaluation_data[1]
    # total
    gon.user_scores = @user_scores
    # issue tags
    gon.issue_tags_labels = @user.issue_tags_labels
    gon.issue_tags_evaluation_datas = @user.issue_tags_evaluation_datas
    # comment tags
    gon.comment_tags_labels = @user.comment_tags_labels
    gon.comment_tags_evaluation_datas = @user.comment_tags_evaluation_datas
  end

  def edit
    @page_title = "Edit profile"
  end

  def update
    if @user.update(user_params)
      redirect_to mypage_path
    else
      flash.now[:error] = "名前が空欄のようです。もう一度お試しください。"
      render 'edit'
    end
  end

  def index
    @page_title = "Users"
    users = @team.users
    @pagenated_users = users.page(params[:page]).per(12)
  end

  private
  def only_team_user
    unless TeamMember.where(team_id: @team).any? {|team| team.user_id == current_user.id}
      redirect_to mypage_path(current_user)
    end
  end

  def only_current_user
    unless @user == current_user
      redirect_to mypage_path(current_user)
    end
  end

  def barrier_trial_user
    if  @user.id == 31
      redirect_to mypage_path(current_user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def team_member_params
    params.require(:team_member).permit(:user_id, :team_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_answer_tab.html.erb
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="answer-tab" role="tablist" aria-orientation="vertical"><%# 回答者 %>
      <a class="nav-link active" id="response-tab" data-toggle="pill" href="#response" aria-controls="response" aria-selected="true">Time to response</a>
      <a class="nav-link" id="required-time-tab" data-toggle="pill" href="#required-time" aria-controls="required-time" aria-selected="false">Time to solved</a>
      <a class="nav-link" id="best-answer-tab" data-toggle="pill" href="#best-answer" aria-controls="best-answer" aria-selected="false">Best answer</a>
      <a class="nav-link" id="comment-tags-tab" data-toggle="pill" href="#comment-tags" aria-controls="comment-tags" aria-selected="false">Tags</a>
    </div>
  </div>

  <div class="col-9">
    <div class="tab-content" id="answer-tabContent"><%# 回答者 %>
      <div class="tab-pane fade show active" id="response" aria-labelledby="response-tab">
        <canvas id="responseChart" style="height:100%;"></canvas>
        <%= javascript_include_tag 'charts/response_chart' %>
      </div>

      <div class="tab-pane fade" id="required-time" aria-labelledby="required-time-tab">
        <canvas id="requiredTimeChart"></canvas>
        <%= javascript_include_tag 'charts/required_time_chart' %>
      </div>

      <div class="tab-pane fade" id="best-answer" aria-labelledby="best-answer-tab">
        <canvas id="bestAnswerChart"></canvas>
        <%= javascript_include_tag 'charts/best_answer_chart' %>
      </div>

      <div class="tab-pane fade" id="comment-tags" aria-labelledby="comment-tags-tab">
        <canvas id="commentTagsChart"></canvas>
        <%= javascript_include_tag 'charts/comment_tags_chart' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_chart_tab.html.erb
<div class="row mt-5 px-5">
  <div class="col-12 offset-md-1 col-md-10">

    <ul id="chartTab" class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a href="#questioner" id="questioner-tab" class="nav-link active" role="tab" data-toggle="tab" aria-controls="questioner" aria-selected="true">
          Questioner
        </a>
      </li>
      <li class="nav-item">
        <a href="#answerer" id="answerer-tab" class="nav-link" role="tab" data-toggle="tab" aria-controls="answerer" aria-selected="false">
          Answerer
        </a>
      </li>
    </ul>

    <div id="chartTabContent" class="tab-content mt-3">
      <div id="questioner" class="tab-pane active" role="tabpanel" aria-labelledby="questioner-tab">
        <%= render 'users/questioner_tab' %>
      </div>

      <div id="answerer" class="tab-pane" role="tabpanel" aria-labelledby="answerer-tab">
        <%= render 'users/answerer_tab' %>
      </div>
    </div>

    <div class="row flex-column align-items-end">
      <%= link_to root_path(anchor: "criteria") do %>
        <i class="far fa-question-circle"></i>
         About evaluation criteria
      <% end %>
    </div>

  </div>
</div>

<%= Gon::Base.render_data %>
<%= javascript_include_tag 'tab_charts', 'data-turbolinks-track': 'reload' %>

app/views/users/_member_card.html.erb
<div class="card">
  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "noimage.jpg", class: "card-img-top " %>
  <div class="card-body">
    <h5 class="card-title"><%= link_to user.name, team_user_path(team, user) %></h5>

    <div class="d-flex justify-content-end">
      <div class="ml-1">
        <i class="fas fa-pen-fancy"></i><%= team.issues.where(user_id: user).count %>
      </div>
      <div class="ml-1">
        <i class="fas fa-comment"></i><%= team.issues.map{|issue| issue.comments.where(user_id: user).count}.sum %>
      </div>
    </div>

  </div>
</div>


app/views/users/_profile_card.html.erb
<div class="card">
  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "noimage.jpg", class: "card-img-top" %>
  <div class="card-body">
    <h5 class="card-title headline"><%= user.name %></h5>
    <p class="card-text"><%= user.introduction %></p>

    <div class="d-flex justify-content-end">
      <div class="ml-2">
        <i class="fas fa-pen-fancy"></i><%= user.issues.count %>
      </div>

      <div class="ml-2">
        <i class="fas fa-comment"></i><%= user.issues.map{|issue| issue.comments.count}.sum %>
      </div>

      <% if user == current_user %>
        <%= link_to edit_user_path(user), class:"btn btn-outline-success btn-sm ml-2" do %>
          <i class="fas fa-cog"></i>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/users/_search_form.html.erb
<%= form_with url: team_users_search_path(team), method: :get, local: true do |f| %>
  <div class="row input-group">
    <%= f.text_field :q, placeholder: "Enter search word.", autofocus: true, class:"form-control col-10" %>
    <div class="input-group-append">
      <%= f.submit "Search", class:"btn btn-danger" %>
    </div>
  </div>
<% end %>
<div class="row justify-content-end">
  <%= link_to "Delete search conditions", team_users_path(team), class:"mr-3" %>
</div>

app/views/users/_total_chart.html.erb
<canvas id="totalChart" width="100%"></canvas>

<%= Gon::Base.render_data %>
<%= javascript_include_tag 'total_chart', 'data-turbolinks-track': 'reload' %>

app/views/users/edit.html.erb
<%= flash[:error] %>

<div class="offset-2 col-8">
  <%= form_with model: current_user do |f| %>

    <p class="headline mt-5">Name</p>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control offset-1 col-10" %>
    </div>

    <p class="headline mt-5">Introduction</p>
    <div class="form-group">
      <%= f.text_area :introduction, class: "form-control offset-1 col-10" %>
    </div>

    <p class="headline mt-5">Image</p>
    <div class="form-group">
      <%= f.attachment_field :profile_image, class: "offset-1 col-10" %>
    </div>

    <%= f.submit "Update profile", class:"btn btn-danger btn-block offset-1 col-10 mt-5" %>
  <% end %>
</div>

<%= link_to "My page", mypage_path, class: "btn btn-dark btn-sm float-left m-5" %>

app/views/users/index.html.erb
<div class="row">
  <div class="offset-2 col-8">
    <%= render 'users/search_form', team: @team %>
  </div>
</div>

<div class="row my-5">
  <div class="offset-1 col-10">
    <div class="card-columns">
      <% @pagenated_users.each do |user| %>
        <%= render 'users/member_card', team: @team, user: user  %>
      <% end %>
    </div>
  </div>
</div>

<div class="row justify-content-center my-5">
  <%= paginate @pagenated_users %>
</div>

app/views/users/my_page.html.erb
<div class="row flex-column align-items-center my-5">
  <h1 class="titlemark">・</h1>
    <% if @team.present? %>
      <h1>User information</h1>
    <% else %>
      <h1>My page</h1>
    <% end %>
  <h1 class="titlemark">・</h1>
</div>

<div class="row mt-5">
  <div class="offset-1 col-4">
    <%= render 'users/profile_card', team: @team, user: @user %>
  </div>
  
  <%= Gon::Base.render_data %>
  <div class="col-7">
    <canvas id="totalChart" style="height:100%;"></canvas>
    <%= render 'users/charts/total_chart' %>
  </div>
</div>

<%# chart tabs %>
<div class="row mt-5">
  <div class="offset-1 col-10">

    <ul id="chartTab" class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a href="#questioner" id="questioner-tab" class="nav-link active" role="tab" data-toggle="tab" aria-controls="questioner" aria-selected="true">
          Questioner
        </a>
      </li>
      <li class="nav-item">
        <a href="#answer" id="answer-tab" class="nav-link" role="tab" data-toggle="tab" aria-controls="answer" aria-selected="false">
          Answer
        </a>
      </li>
    </ul>

    <div id="chartTabContent" class="tab-content mt-3">
      <div id="questioner" class="tab-pane active" role="tabpanel" aria-labelledby="questioner-tab">
        <%= render 'users/charts/questioner_tab' %>
      </div>

      <div id="answer" class="tab-pane" role="tabpanel" aria-labelledby="answer-tab">
        <%= render 'users/charts/answer_tab' %>
      </div>
    </div>

  </div>
</div>

app/views/users/mypage.html.erb
<div class="row">
  <div class="offset-1 col-10">
    <p class="headline">Teams</p>

    <div class="row">
      <div class="col-12 col-md-8 px-5">
        <% @teams.each do |team| %>
          <%= link_to team_issues_path(team), class:"h4" do %>
            <div class="mr-auto my-1">
              <i class="fas fa-flag"></i>
              <%= team.name %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="col-12 mt-5 col-md-4 mt-md-0">
        <span class="titlemark">
          <%= flash[:error] %>
        </span>

        <%= form_with model: @new_team_mamber, url: join_team_path do |f| %>
          <div class="form-group">
            <%= f.text_field :team_name, placeholder: "Team name", class:"form-control offset-1 col-10" %>
            <%= f.text_field :team_id, placeholder: "Team id", class:"form-control offset-1 col-10 mt-3" %>
            <div class="row flex-column align-items-center mt-3">
              <%= f.submit "Join team!", class:"btn btn-sm btn-dark" %>
            </div>
          </div>
        <% end %>

        <div class="row flex-column align-items-end">
          <%= link_to root_path(anchor: 'about') do %>
            <i class="far fa-question-circle"></i>
            Which team can you join?
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="row mt-5">
  <div class="offset-1 col-10">
    <p class="headline">Profile</p>

    <div class="row mt-5 px-5">
      <div class="col-xs-12 col-md-4">
        <%= render 'users/profile_card', team: @team, user: @user %>
      </div>

      <div class="col-12 mt-5 col-md-8 mt-md-0">
        <%= render 'charts/user_charts' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="offset-1 col-10">
    <p class="headline">Profile</p>

    <div class="row mt-5 px-5">
      <div class="col-xs-12 col-md-4">
        <%= render 'users/profile_card', team: @team, user: @user %>
      </div>

      <div class="col-12 mt-5 col-md-8 mt-md-0">
        <%= render 'charts/user_charts' %>
      </div>
    </div>
  </div>
</div>

<div class="row mt-5">
  <div class="offset-1 col-10">
    <p class="headline">Evaluations</p>

    <div class="col-12 offset-md-1 col-md-10 mt-5">
      <%= render 'charts/team_charts' %>
    </div>
  </div>
</div>