config/routes.rb
Rails.application.routes.draw do

  # home
  root 'home#top'
  get '/about' => 'home#about'

  # users
  devise_for :users
  resources :users, only: [:update], param: :user_id
  resources :users, only: [] do
    resources :comments, only: [:index]
    resources :issues, only: [:index]
  end
  get 'mypage/:user_id' => 'users#mypage', as: "mypage"
  get 'mypage/:user_id/edit' => 'users#edit', as: "edit_user"
  post 'mypage/:user_id/join_team' => 'users#join_team', as: "join_team"

  # search
  get 'teams/:team_id/issues/search' => 'search#issues', as: "team_issues_search"
  get 'teams/:team_id/users/search' => 'search#users', as: "team_users_search"
  get 'teams/:team_id/tags/search' => 'search#tags', as: "team_tags_search"

  # teams
  resources :teams, only: [:show], param: :team_id
  resources :teams, only: [] do
  # teams/users
    resources :users, only: [:index, :show], param: :user_id
    resources :users, only: [] do
      resources :comments, only: [:index]
      resources :issues, only: [:index]
    end
  # teams/tags
    resources :tags, only: [:index, :create] do
      resources :issues, only: [:index]
    end
  # teams/issues
    resources :issues, param: :issue_id
    resources :issues, only: [] do
      resources :comments, only: [:create, :edit, :update, :destroy], param: :comment_id
      resource :likes, only: [:create, :destroy]
    end
    get '/issues/:issue_id/choice' => 'issues#choice', as: "choice"
    get '/issues/:issue_id/confirm' => 'issues#confirm', as: "confirm"
    put '/issues/:issue_id/settled' => 'issues#settled', as: "settled"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_responsive_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to root_path do %>
      <%= image_tag 'logo-white.png', width: '50', class:"navbar-brand" %>
    <% end %>

    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="Navber">
      <div class="navbar-nav">
        <% if user_signed_in? && @team.present? %>
          <a href="#" class="nav-link dropdown-toggle h3" role="button" data-toggle="dropdown" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-flag"></i>
            <%= @team.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to team_issues_path(@team), class:"dropdown-item" do %>
              <i class="fas fa-clipboard-list"></i>
              Issues
            <% end %>

            <%= link_to team_tags_path(@team), class:"dropdown-item" do %>
              <i class="fas fa-tags"></i>
              Tags
            <% end %>

            <%= link_to team_users_path(@team), class:"dropdown-item" do %>
              <i class="fas fa-users"></i>
              Users
            <% end %>

            <%= link_to mypage_path(current_user), class:"dropdown-item" do %>
              <i class="fas fa-running"></i>
              Leave team
            <% end %>
          </div>

          <%= link_to new_team_issue_path(@team), class:"nav-link" do %>
            <i class="fas fa-plus-circle"></i>
            New issue
          <% end %>

          <%= link_to team_user_path(@team, current_user), class:"nav-link" do %>
            <i class="fas fa-id-card"></i>
            My page
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>
            <i class="fas fa-sign-out-alt"></i>
            Sign out
          <% end %>

        <% elsif user_signed_in? %>
          <%= link_to root_path, class:"nav-link" do %>
            <i class="fas fa-home"></i>
            Home
          <% end %>

          <%= link_to mypage_path(current_user), class:"nav-link" do %>
            <i class="fas fa-id-card"></i>
            My page
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>
            <i class="fas fa-sign-out-alt"></i>
            Sign out
          <% end %>

        <% else %>
          <%= link_to root_path, class:"nav-link" do %>
            <i class="fas fa-home"></i>
            Home
          <% end %>

          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt"></i>
            Sign in
          <% end %>

          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <i class="fas fa-user-plus"></i>
            Sign up
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</nav>

app/views/layouts/_signin_sidebar.html.erb
<div class="sidebar bg-dark d-flex">
  <nav class="nav flex-column align-items-center col-12">

    <div class="row mt-5">
      <%= link_to root_path do %>
        <%= image_tag 'logo-white.png', width: '100' %>
      <% end %>
    </div>

    <div class="nav-items mt-5">
      <% if @team.present? %>
        <a href="#" class="nav-link dropdown-toggle h3" role="button" data-toggle="dropdown" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-flag"></i>
          <%= @team.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to team_issues_path(@team), class:"dropdown-item" do %>
            <i class="fas fa-clipboard-list"></i>
            Issues
          <% end %>

          <%= link_to team_tags_path(@team), class:"dropdown-item" do %>
            <i class="fas fa-tags"></i>
            Tags
          <% end %>

          <%= link_to team_users_path(@team), class:"dropdown-item" do %>
            <i class="fas fa-users"></i>
            Users
          <% end %>

          <%= link_to mypage_path(current_user), class:"dropdown-item" do %>
            <i class="fas fa-running"></i>
            Leave team
          <% end %>
        </div>

        <%= link_to new_team_issue_path(@team), class:"nav-link" do %>
          <i class="fas fa-plus-circle"></i>
          New issue
        <% end %>

        <%= link_to team_user_path(@team, current_user), class:"nav-link" do %>
          <i class="fas fa-id-card"></i>
          My page
        <% end %>

      <% else %>
        <%= link_to root_path, class:"nav-link" do %>
          <i class="fas fa-home"></i>
          Home
        <% end %>

        <%= link_to mypage_path(current_user), class:"nav-link" do %>
          <i class="fas fa-id-card"></i>
          My page
        <% end %>

      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class:"nav-link" do %>
        <i class="fas fa-sign-out-alt"></i>
        Sign out
      <% end %>
    </div>

    <div class="row mt-auto mb-3">
      <p class="text-white">© 2020 Kanon inc.</p>
    </div>
  </nav>
</div>

app/views/layouts/_signout_sidebar.html.erb
<div class="sidebar bg-dark d-flex">
  <nav class="nav flex-column align-items-center col-12">

    <div class="row mt-5">
      <%= link_to root_path do %>
        <%= image_tag 'logo-white.png', width: '100' %>
      <% end %>
    </div>

    <div class="nav-items mt-5">
      <%= link_to root_path, class:"nav-link" do %>
        <i class="fas fa-home"></i>
        Home
      <% end %>

      <%= link_to new_user_session_path, class: "nav-link" do %>
        <i class="fas fa-sign-in-alt"></i>
        Sign in
      <% end %>

      <%= link_to new_user_registration_path, class: "nav-link" do %>
        <i class="fas fa-user-plus"></i>
        Sign up
      <% end %>
    </div>

    <div class="row mt-auto mb-3">
      <p class="text-white">© 2020 Kanon inc.</p>
    </div>
  </nav>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToT</title>
    <link rel="icon" href="<%= asset_path "favicon.ico" %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f8b5a013fa.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- responsive header -->
    <header class="d-md-none">
      <%= render 'layouts/responsive_header' %>
    </header>
    <div class="row">
      <!-- sidebar -->
      <div class="col-md-3 d-none d-md-block">
        <% if user_signed_in? %>
          <%= render 'layouts/signin_sidebar' %>
        <% else %>
          <%= render 'layouts/signout_sidebar' %>
        <% end %>
      </div>

      <!-- body -->
      <main class="col-xs-12 col-md-9">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <% unless controller_name == 'home' %>
          <div class="row flex-column align-items-center my-5">
            <h1 class="titlemark">・</h1>
              <h1><%= @page_title %></h1>
            <h1 class="titlemark">・</h1>
          </div>
        <% end %>

        <%= yield %>
      </main>
    </div>

  </body>
</html>